from google_auth_oauthlib.flow import InstalledAppFlow

from googleapiclient.discovery import build

from datetime import datetime, timedelta


# ==========================================
# GOOGLE CALENDAR SCOPES
# ==========================================

SCOPES = [
    "https://www.googleapis.com/auth/calendar"
]


# ==========================================
# GOOGLE AUTH
# ==========================================

def authenticate_google_calendar():

    flow = InstalledAppFlow.from_client_secrets_file(

        "client_secret1.json",

        scopes=SCOPES

    )

    credentials = flow.run_local_server(
        port=0
    )

    service = build(
        "calendar",
        "v3",
        credentials=credentials
    )

    return service


# ==========================================
# CREATE CALENDAR EVENTS
# ==========================================

def sync_study_plan_to_calendar(plan_json):

    service = authenticate_google_calendar()

    for study_day in plan_json["days"]:

        date = study_day["date"]

        start_time = study_day["start_time"]

        end_time = study_day["end_time"]

        topic = study_day["topic"]

        # ==========================================
        # DATETIME CONVERSION
        # ==========================================

        start_datetime = datetime.strptime(

            f"{date} {start_time}",

            "%Y-%m-%d %I:%M %p"

        )

        end_datetime = datetime.strptime(

            f"{date} {end_time}",

            "%Y-%m-%d %I:%M %p"

        )

        # ==========================================
        # EVENT BODY
        # ==========================================

        event = {

            "summary": f"Study: {topic}",

            "description": (
                "Generated by StudyPilot"
            ),

            "start": {

                "dateTime":
                    start_datetime.isoformat(),

                "timeZone":
                    "Asia/Kolkata"

            },

            "end": {

                "dateTime":
                    end_datetime.isoformat(),

                "timeZone":
                    "Asia/Kolkata"

            }

        }

        # ==========================================
        # INSERT EVENT
        # ==========================================

        service.events().insert(

            calendarId="primary",

            body=event

        ).execute()

    return (
        "Study plan synced "
        "to Google Calendar!"
    )
print("hello world")